name: LIDAR COPC Validation

on:
  workflow_dispatch:
    inputs:
      copc_url:
        description: 'URL to COPC.laz file'
        required: true
        type: string

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Verify COPC URL
      run: |
        if [[ ! "${{ github.event.inputs.copc_url }}" =~ \.copc\.laz$ ]]; then
          echo "Error: Provided URL does not end with .copc.laz"
          exit 1
        fi
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: '3.12'
        environment-file: environment.yml
        activate-environment: lidar-env

    - name: Download COPC file
      run: |
        wget --quiet --retry-connrefused --waitretry=5 --timeout=30 --tries=5 "${{ github.event.inputs.copc_url }}" -O input.copc.laz

    - name: Run validation script
      run: |
        source "$HOME/miniconda3/etc/profile.d/conda.sh"
        conda activate lidar-env
        python check_impulsions.py input.copc.laz

    - name: Upload CSV artifacts
      uses: actions/upload-artifact@v4
      with:
        name: validation-results
        path: |
          impulsions_inconsistent_NumberOfReturns.csv
          impulsions_count_mismatch.csv
